# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'Kristian Schmidt'
description:      'My technical writings. So far mostly about F#'
url:              http://www.kreutz.us
baseurl:          /

author:
  name:           'Kristian Schmidt'
  url:            https://twitter.com/KreutzSchmidt

paginate:          5
excerpt_separator: <!--more-->

# Custom vars

github:
  repo:           https://github.com/KristianSchmidt/KristianSchmidt.github.io

gems: [jekyll-paginate]